import '@/styles/globals.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'
import { ThemeProvider } from '@mui/material/styles';
import theme from '../utils/theme'
import { useEffect, useState } from 'react';
import { MOBILE_WIDTH } from '@/utils/constants';
export default function App({ Component, pageProps }: AppProps) {
  const [width, setWidth] = useState<number>(0);

  const handleWindowSizeChange=()=> {
    setWidth(window.innerWidth);
  }

  useEffect(() => {
    window.addEventListener('resize', handleWindowSizeChange);
    return () => {
      window.removeEventListener('resize', handleWindowSizeChange);
    }
  }, []);

  const isMobileCheck = width <= MOBILE_WIDTH;

  const allProps ={
    isMobile: isMobileCheck,
    ...pageProps
  }

  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Fin Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...allProps} />
    </ThemeProvider>
  )

}
